version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/node:18
    environment:
      CI: true
      TEST_DB: $TEST_DB
      SECRET: $SECRET
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
        
      - run: npm ci
      - run: npm run build --if-present
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test
      - run:
          name: Load environment variables
          command: |
            source .env

